[package]
name = "trace-var"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version="1", features = ["nightly"]}
quote = "1"
syn = {version = "2", features=["fold", "full"]}
