services:
  postgres:
    env_file:
      - .env
    container_name: $CONTAINER_NAME
    restart: always
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - "./database:/var/lib/postgresql/data"
