[package]
name = "use_inquire"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
inquire = { version = "0.7", features = ["date", "editor"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
