[package]
name = "lazy-static"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.92", features = ["nightly", "proc-macro"] }
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full"] }
