[package]
name = "dump-syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
proc-macro2 = { version = "1.0.92", features = ["span-locations"] }
syn = { version = "2.0.90", default-features = false, features = [
  "extra-traits",
  "full",
  "parsing",
] }
