[package]
name = "use_tokio"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
bytes = "1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["codec"] }
