[package]
name = "use_crossterm"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
futures-timer = "3.0.3"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
